#server:
#  port: 7000
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#
#org:
#  my:
#    jwt:
#      skip-auth-urls:      #跳过认证的路由
#        - /baidu
#        - /login
##      ############################################
##      #   有效时长
##      #     单位：d:天、h:小时、m:分钟、s:秒
##      ###########################################
#      effective-time: 20m
